apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sliples-postgres-pvc
  namespace: sliples
  labels:
    app.kubernetes.io/name: sliples
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set the storage class appropriate for your cluster
  # storageClassName: standard
