map $http_origin $cors_origin {
    default "";
    "https://staging.crunchpayments.com:8443" $http_origin;
    "https://crunchdev.crunchpayments.com" $http_origin;
    "https://login.crunchpayments.com" $http_origin;
    "https://ctsdev.crunchpayments.com" $http_origin;
    "https://ctsuat.crunchpayments.com" $http_origin;
    "https://giftstarrstaging.crunchpayments.com" $http_origin;
    "https://giftstarruat.crunchpayments.com" $http_origin;
}



server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /ui-log {

        add_header Access-Control-Allow-Origin $cors_origin always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        if ($request_method = OPTIONS) {
            return 204;
        }
    }

    
    # Security headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
}
