apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sliples-frontend
  labels:
    app: sliples
    component: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Clevacard/sliples.git
      ref: main
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: sliples-frontend:latest
  triggers:
    - type: ConfigChange
