apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sliples-frontend
  namespace: sliples
  labels:
    app.kubernetes.io/name: sliples
    app.kubernetes.io/component: frontend
spec:
  host: sliples.agantis.in
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
