apiVersion: v1
kind: Service
metadata:
  name: browser-firefox
  namespace: sliples
  labels:
    app.kubernetes.io/name: sliples
    app.kubernetes.io/component: browser-firefox
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sliples
    app.kubernetes.io/component: browser-firefox
  ports:
    - name: ws
      port: 3000
      targetPort: ws
      protocol: TCP
